version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=smartlibrary
      - POSTGRES_USER=smartuser
      - POSTGRES_PASSWORD=smartpass
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://smartuser:smartpass@db:5432/smartlibrary
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A config worker -l INFO
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://smartuser:smartpass@db:5432/smartlibrary
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DEBUG=False
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A config beat -l INFO
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://smartuser:smartpass@db:5432/smartlibrary
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DEBUG=False
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
