# Generated by Django 6.1.1 on 2026-09-09 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_organization_book_organization_and_more'),
        ('organizations', '0002_alter_branch_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=64)),
                ('accession_number', models.CharField(blank=True, max_length=64)),
                ('shelf_location', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ISSUED', 'Issued'), ('RESERVED', 'Reserved'), ('LOST', 'Lost'), ('DAMAGED', 'Damaged'), ('MAINTENANCE', 'Maintenance'), ('ARCHIVED', 'Archived')], default='AVAILABLE', max_length=20)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=20)),
                ('acquired_date', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Book copies',
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['organization', 'status'], name='books_book_organiz_d02c6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(condition=models.Q(('isbn', ''), _negated=True), fields=('organization', 'isbn'), name='uniq_isbn_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_category_name_per_organization'),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='books.book'),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_copies', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_copies', to='organizations.organization'),
        ),
        migrations.AddConstraint(
            model_name='bookcopy',
            constraint=models.UniqueConstraint(fields=('organization', 'barcode'), name='uniq_barcode_per_organization'),
        ),
    ]
