# Generated by Django 6.0.8 on 2026-09-11 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookcopy_book_books_book_organiz_d02c6b_idx_and_more'),
        ('organizations', '0002_alter_branch_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='digital_books/')),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('EPUB', 'EPUB')], max_length=10)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('requires_drm', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_asset', to='books.book')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_assets', to='organizations.organization')),
            ],
        ),
    ]
