# Generated by Django 6.0.8 on 2026-09-17 03:44

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_digitalasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=config.utils.GenerateSafeFilename('authors/')),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=config.utils.GenerateSafeFilename('books/covers/')),
        ),
        migrations.AlterField(
            model_name='digitalasset',
            name='file',
            field=models.FileField(upload_to=config.utils.GenerateSafeFilename('digital_books/')),
        ),
    ]
