# Generated by Django 6.0.8 on 2026-09-17 03:45

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_branch_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=config.utils.GenerateSafeFilename('organizations/logos/')),
        ),
    ]
