# Generated by Django 6.1.1 on 2026-09-09 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookcopy_book_books_book_organiz_d02c6b_idx_and_more'),
        ('organizations', '0002_alter_branch_options_alter_organization_options_and_more'),
        ('reservations', '0002_reservation_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='queue_position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WAITING', 'Waiting'), ('AVAILABLE', 'Available'), ('APPROVED', 'Approved'), ('COLLECTED', 'Collected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['organization', 'status'], name='reservation_organiz_cbafb6_idx'),
        ),
    ]
