# Generated by Django 6.1.1 on 2026-09-07 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(default='SmartLibrary', max_length=255)),
                ('library_email', models.EmailField(default='admin@smartlibrary.com', max_length=254)),
                ('library_phone', models.CharField(default='+1234567890', max_length=20)),
                ('library_address', models.TextField(default='123 Library Street')),
                ('max_books_per_member', models.PositiveIntegerField(default=3)),
                ('default_borrow_days', models.PositiveIntegerField(default=14)),
                ('fine_per_day', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('library_logo', models.ImageField(blank=True, null=True, upload_to='settings/logo/')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
