# Generated by Django 6.1.1 on 2026-09-09 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_activitylog_organization_systemsetting_organization'),
        ('organizations', '0002_alter_branch_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='allow_self_renewal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='enable_late_fines',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='overdue_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='password_min_length',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='primary_color',
            field=models.CharField(default='#111111', max_length=7),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='renewal_limit',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='require_2fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='reservation_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='secondary_color',
            field=models.CharField(default='#10B981', max_length=7),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_settings', to='organizations.organization'),
        ),
    ]
