# Generated by Django 6.1.1 on 2026-09-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_branch_user_organization_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_all_branches',
            field=models.BooleanField(default=False, help_text='When enabled, staff may manage transactions across all branches in their organization.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
