# Generated by Django 6.0.8 on 2026-09-11 04:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_digitalasset'),
        ('organizations', '0002_alter_branch_options_alter_organization_options_and_more'),
        ('transactions', '0003_fine_transaction_book_copy_transaction_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('access_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='books.digitalasset')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_loans', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_loans', to='organizations.organization')),
            ],
        ),
    ]
