# Generated by Django 6.0.8 on 2026-09-17 03:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('DAILY_CIRCULATION', 'Daily Circulation'), ('WEEKLY_SUMMARY', 'Weekly Library Summary'), ('MONTHLY_SUMMARY', 'Monthly Library Summary'), ('OVERDUE_BOOKS', 'Overdue Books'), ('OUTSTANDING_FINES', 'Outstanding Fines'), ('NEW_MEMBERS', 'New Members'), ('POPULAR_BOOKS', 'Popular Books'), ('INVENTORY_STATUS', 'Inventory Status'), ('CUSTOM', 'Custom Report')], default='CUSTOM', max_length=50)),
                ('recipients', models.TextField(help_text='Comma separated email addresses')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=20)),
                ('format', models.CharField(choices=[('CSV', 'CSV'), ('PDF', 'PDF'), ('BOTH', 'CSV + PDF')], default='CSV', max_length=10)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('scheduled_time', models.TimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('EMAIL_FAILED', 'Email Failed'), ('GENERATING', 'Generating')], default='GENERATING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('format_generated', models.CharField(max_length=10)),
                ('record_count', models.IntegerField(default=0)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.scheduledreport')),
            ],
        ),
    ]
