# Generated by Django 6.1.1 on 2026-09-09 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_memberprofile_organization'),
        ('organizations', '0002_alter_branch_options_alter_organization_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='home_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='member_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_profiles', to='organizations.organization'),
        ),
        migrations.AddConstraint(
            model_name='memberprofile',
            constraint=models.UniqueConstraint(fields=('organization', 'member_id'), name='uniq_member_id_per_organization'),
        ),
    ]
