# Generated by Django 6.0.8 on 2026-09-10 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_organization'),
        ('organizations', '0002_alter_branch_options_alter_organization_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('SUCCESS', 'Success'), ('DANGER', 'Danger'), ('EMAIL', 'Email Sent')], default='INFO', max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_due_soon', models.BooleanField(default=True)),
                ('email_overdue', models.BooleanField(default=True)),
                ('email_reservation_ready', models.BooleanField(default=True)),
                ('email_fines', models.BooleanField(default=True)),
                ('in_app_due_soon', models.BooleanField(default=True)),
                ('in_app_overdue', models.BooleanField(default=True)),
                ('in_app_reservation_ready', models.BooleanField(default=True)),
                ('in_app_fines', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('DUE_SOON', 'Due Soon'), ('OVERDUE', 'Overdue'), ('RESERVATION_READY', 'Reservation Ready'), ('FINE_CREATED', 'Fine Created'), ('PAYMENT_RECEIVED', 'Payment Received'), ('WELCOME', 'Welcome Email')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField(help_text='Use {{ user.first_name }}, {{ book.title }}, etc. for variables.')),
                ('body_text', models.TextField(help_text='Plain text fallback.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='organizations.organization')),
            ],
            options={
                'unique_together': {('organization', 'event_type')},
            },
        ),
    ]
